version: '3'
services:
  database:
    image: postgres:16.1-bookworm
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: tunainuser
      POSTGRES_PASSWORD: tunainpass
      POSTGRES_DB: tunaindb
    command: -p 5432
    # volumes:
    #   - ./backend/init-data.sql:/docker-entrypoint-initdb.d/init-data.sql
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3,sqs
      # - AWS_DEFAULT_REGION=eu-west-1
      # - SMTP_HOST=localhost:1025
      # - SMTP_EMAIL=local@localstack.local
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack-volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"