# Generated by Django 4.2.7 on 2023-11-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunain', '0002_alter_page_user_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
