# Generated by Django 4.2.7 on 2023-11-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunain', '0003_page_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='The 5th Elara revolution', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
