# Generated by Django 4.2.7 on 2023-11-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunain', '0005_alter_page_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
